### PR TITLE
Added option for sorting shows in folders

### PR DESCRIPTION
**Pull request by tcard**
For the moment I just added a checkbox in the preferences tab. I tried to translate the label to Spanish but it doesn't seem to work and I really have not idea about what is failing, I think you'll do it a lot faster. I also fixed a few lower errors I found diving into the code.

I'm Harad from the GReader Gang, btw :P

### CODE REVIEW

**Comment by victorpimentel** [comment]
Thank you Harad! Two things I don't quite understand:
- Why adding the <NSAnimationDelegate> to MBSliderButton? Did you use Xcode3 or Xcode4?
- And why removing like 1500 lines of the interface?

The «create a folder stuff» seems to be working, although I have to try it. Also I don't know if it should be better to do it before or inside the startDownloadingURL function, but anyway there is so much duplicated code I want to refactor a lot of things.

Anyway, yes, I will be faster with the "add an option" paraphernalia, it's like 15 minutes or so to change all the files because I have already done it like four times :P

**Comment by tcard** [comment]
I use Xcode 4 and I was getting a warning on this line at MBSliderButton.m, animateTo: `[a setDelegate:self];`. Setting itself as delegate requires obviously declaring the interface as NSAnimationDelegate compliant.

I agree, the code is a little mess at the moment and needs a serious look through, I realize that my approach wasn't too much elegant but it's a whole project issue. I put it outside the startDownloadingURL function because I wanted to change as less amount of code as possible.

**Comment by tcard** [comment]
I forgot to mention, I just edited the xib in order to add the checkbox and nothing more :\ I guess that all that code removal is just Interface Builder internal behavior in some way. It works, though.

**Comment by victorpimentel** [comment]
I added these changes here:

https://github.com/victorpimentel/TVShows/commit/cddd90bb40d05a2f7bef784deaa3979e353af695

I had to use a different commit instead of a clean merge because it needed several changes. And I was so late because I wanted to end the work in another thing :P

**Pull request closed without merging**
